### PR TITLE
(PA-2875) bump Ruby from 2.4.3 to 2.4.7

### PR DESCRIPTION
**Pull request by gimmyxd**
Also renamed the patches folder to match
Ruby minor version: 243 -> 24

Reapplied patches:
 - aix_revert_configure_in_changes.patch
 - update_rbinstall_for_windows.patch
 - windows_ruby_2.4_fixup_generated_batch_files.patch

### CODE REVIEW

**Comment by gimmyxd** [comment]
had a first good run for a subset of agent-runtime-5.5.x platforms here: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/578/

**Comment by gimmyxd** [comment]
can someone from @puppetlabs/bolt @puppetlabs/pdk verify that this is needed and is not breaking bolt-runtime and pdk-rutime?

**Comment by scotje** [comment]
Some changes will need to be made to version numbers in the `pdk-runtime` project config.

**Comment by scotje** [comment]
@rodjek can you look at what needs to be updated here?

**Pull request merged**
