### PR TITLE
(PA-3080) removal of older obsolete platforms and fedora28

### PR DESCRIPTION
**Pull request by ciprianbadescu**

### CODE REVIEW

**Comment by donoghuc** [comment]
Currently the only mac platforms we build and ship pe-client-tools for is osx 10.12 and 10.13. When is this scheduled to be merged? Is there a ticket number to look at?

**Comment by gimmyxd** [comment]
@donoghuc https://tickets.puppetlabs.com/browse/PA-3096

We won't remove this platforms if other teams are still using them.

**Comment by McdonaldSeanp** [comment]
@gimmyxd @donoghuc we should update client-tools so that it matches agent support. https://tickets.puppetlabs.com/browse/PE-28365 is open to add support for the newer OSes. Skeletor will work to get that updated soon so we can merge this and deprecate these platforms.

**Comment by ciprianbadescu** [comment]
@donoghuc , I moved fedora 29 and osx 12,13 to separate PR https://github.com/puppetlabs/puppet-runtime/pull/303

**Comment by beechtom** [comment]
Bolt currently has PRs up to stop building and testing on these platforms.

https://github.com/puppetlabs/ci-job-configs/pull/6797
https://github.com/puppetlabs/bolt-vanagon/pull/132

**Pull request merged**
