### PR TITLE
(PE-24779) Add pe-client-tools-runtime

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds the pe-client-tools-runtime, for use in future PE releases.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This needs some work, like not pointing to pe-client-tools-vanagon#master.

**Comment by underscorgan** [comment]
This looks reasonable! Also, branch names are fine to have in here.

**Comment by MikaelSmith** [comment]
Latest version pushed.

**Comment by MikaelSmith** [comment]
@nicklewis mind taking a look at some point?

**Comment by smcclellan** [comment]
@MikaelSmith This seems to require a rebase.

**Comment by MikaelSmith** [comment]
I'm going to come back to this, but hasn't been my focus recently. Maybe in a few weeks.

**Comment by MikaelSmith** [comment]
I believe this is fixed up, running it through a Windows build still.

**Comment by MikaelSmith** [comment]
Now builds on macOS, Windows, and Linux.

**Comment by MikaelSmith** [comment]
Testing at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1615/.

**Comment by MikaelSmith** [comment]
Windows build wasn't including zlib, fixed that.

**Comment by MikaelSmith** [comment]
I've tested this on several platforms with pe-client-tools, it looks good.

**Comment by underscorgan** [comment]
@MikaelSmith is there anyone else on your team you want review from? Might also be good to get a review from @caseywilliams since she's done a lot of work with this project

**Comment by MikaelSmith** [comment]
Updated with new icu version and ticket number.

**Comment by nicklewis** [comment]
This looks reasonable to me.

**Pull request merged**
