### PR TITLE
(PA-2473) Update curl to 7.64.0.

### PR DESCRIPTION
**Pull request by tavilarion**

### CODE REVIEW

**Comment by bmjen** [comment]
@speedofdark background info can be obtained from the JIRA ticket in the title.

**Comment by speedofdark** [comment]
Understood, but a 1-liner in the PR itself doesn't hurt :) ...

**Comment by caseywilliams** [comment]
curl release notes are all available on the curl site, and I don't think updating a vendored dependency to the latest version really needs much more info than this - I'm ready to merge this whenever the label's gone

**Comment by bmjen** [comment]
@tavilarion What's the cause for the `do not merge` label? What is the ETA on when this can be merged? Hoping to get this into a PDK release next week.

**Comment by tavilarion** [comment]
Waiting for a successful run of the ad-hoc pipeline to make sure this doesn't break anything. This will be merged this week if there are no issues.

**Comment by tavilarion** [comment]
Passing pipeline:
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/563/

There are known issues with solaris, so all is green, this can be merged.

**Pull request merged**
