### PR TITLE
Ship updated gem components for bolt/bolt-server runtimes

### PR DESCRIPTION
**Pull request by donoghuc**
Keep up to date with latest gem releases for bolt/bolt-server packages.

### CODE REVIEW

**Comment by donoghuc** [comment]
I notice that `gettext-setup` has an update too, (`0.29 -> 0.30') https://github.com/puppetlabs/gettext-setup-gem/compare/0.30...0.31 . But that is used by more than just bolt. Is that something we want to pull in across the board?

**Comment by caseywilliams** [comment]
oh, I didn't see your gettext command - I'd want to just go ahead and update it globally, but if people are nervous about that we could introduce the versioning pattern we're using for some other components for gettext

**Comment by lucywyman** [comment]
I agree with updating globally - it seems easy enough to revert and rebuild if something goes wrong.

**Comment by donoghuc** [comment]
Ok, I will follow up with @puppetlabs/night-s-watch about updating `gettext-setup`. For now, the changes to that gem don't impact bolt at all so i'm going to merge this so we can get packages built for release.

**Pull request merged**
