### PR TITLE
(PA-3244) Update boost to version 1.73.0

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
Boost 1.69 contained a bug where there was a possibility for websocketpp to
enter an infinite loop due to the code expecting a boost call to fail when it
wasn't.

https://github.com/chriskohlhoff/asio/issues/261 has more details on the
specific boost call that failed, but there are cases where websocketpp should
be failing when calling async_read because a socket is closed, but the boost
call would not fail.

This commit updates the boost library to latest (1.73.0) since there are fixes
in newer boost versions to remedy the underlying issue.

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
https://github.com/puppetlabs/puppet-agent/pull/1908 should be merged (and merged up) first

**Comment by McdonaldSeanp** [comment]
jenkins please test this with puppet-agent#master on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,debian8-64a,debian8-32a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,ubuntu1804-64a,ubuntu2004-64a,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by steveax** [comment]
jenkins please test this with puppet-agent#master on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,debian8-64a,debian8-32a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,ubuntu1804-64a,ubuntu2004-64a,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this with puppet-agent#master on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,debian8-64a,debian8-32a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,ubuntu1804-64a,ubuntu2004-64a,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by GabrielNagy** [comment]
jenkins please test this with puppet-agent#master on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa

**Comment by GabrielNagy** [comment]
jenkins please test this with puppet-agent#master on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#master solaris10-64a,solaris11-64a,solaris114-64a

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#master on solaris10-64a,solaris11-64a,solaris114-64a

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#master on solaris10-64a,solaris11-64a,solaris114-64a

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#master on solaris10-64a,solaris11-64a,solaris114-64a

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#master on solaris10-64a,solaris11-64a,solaris114-64a

**Comment by gimmyxd** [comment]
This should fix boost on Solaris 10 and 11 i386, still looking into solaris sparc as it seems to have a too old g++ which does not support std=c++11

**Pull request merged**
