### PR TITLE
(maint) support building pdk and bolt runtimes on osx arm64

### PR DESCRIPTION
**Pull request by h0tw1r3**

### CODE REVIEW

**Comment by joshcooper** [comment]
Thanks @h0tw1r3! Could you run vanagon generic builder for each project on one macOS ARM platform?

**Comment by h0tw1r3** [comment]
[successful osx-14-arm64 pdk-runtime build](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2568/)
[successful osx-14-arm64 bolt-runtime build](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2569/)

**Comment by h0tw1r3** [comment]
https://github.com/puppetlabs/puppet-runtime/pull/768

**Comment by h0tw1r3** [comment]
https://github.com/puppetlabs/bolt/issues/3264

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
