### PR TITLE
(maint) Remove agent-runtime 5.5.x and ruby 2.4.10

### PR DESCRIPTION
**Pull request by joshcooper**
This is blocked on dropping puppet 5 in pdk some time later in 2022

### CODE REVIEW

**Comment by joshcooper** [comment]
- [ ] Drop openssl-fips component

**Review by chelnak — APPROVED** [review]
From a PDK perspective, we are now happy for this to be removed in future versions! 🎉

**Review by binford2k — APPROVED** [review]

**Comment by chelnak** [comment]
@joshcooper How do you feel about getting this merged next week?

**Comment by joshcooper** [comment]
sure thing, we'll get this merged as soon as we get CI back into a stable state.

**Comment by chelnak** [comment]
Winner thank you 😊

**Review by mhashizume — APPROVED** [review]

**Pull request merged**
