### PR TITLE
update snyk github action to 2.2.0

### PR DESCRIPTION
**Pull request by LivingInSyn**

### CODE REVIEW

**Comment by joshcooper** [comment]
@LivingInSyn we're looking to expand the snyk action to other vanagon repos. Should we hold off until this is merged?

**Comment by LivingInSyn** [comment]
@joshcooper this one is ready now, I had forgotten about it

**Comment by joshcooper** [comment]
PR seems to be failing trying to load a non-existent platform config: 

```
/home/travis/.rvm/gems/ruby-2.7.1/gems/vanagon-0.25.0/lib/vanagon/platform/dsl.rb:92:in `read': No such file or directory @ rb_sysopen - /home/travis/.rvm/gems/ruby-2.7.1/gems/vanagon-0.25.0/lib/vanagon/platform/defaults/osx-10.14-x86_64.rb (Errno::ENOENT)
```

Maybe try to rebase your PR against `puppet-runtime#master`?

**Comment by LivingInSyn** [comment]
@joshcooper pulled master into this branch

**Comment by joshcooper** [comment]
@LivingInSyn I was confused by commit 5868259 bumping to 2.2.1 but then a later commit changed it to 2.2.0. Could you squash those commits?

**Comment by LivingInSyn** [comment]
@joshcooper it was a bump from `2.1.1` to `2.2.0`.

**Comment by joshcooper** [comment]
Ah creating a merge commit in your feature branch complicates the overall git history when it's merged. We generally prefer rebasing feature branches to the HEAD of the base branch, so it's clear what's being merged vs what's already merged. To rebase you can do:

```
$ git checkout snyk_scan_update

$ git reset --hard 1d47945
HEAD is now at 1d47945 update version, fix fetch depth

$ git rebase --onto origin/master 2a73942
First, rewinding head to replay your work on top of it...
Applying: update workflow to 2.1.1
Applying: update version, fix fetch depth
```

Then to squash the commits:

```
$ git reset --hard HEAD~2
HEAD is now at a5905d4 Merge pull request #514 from mhashizume/PA-4187/windows_gems

$ git merge --squash HEAD@{1}
Updating a5905d4..8dd8757
Fast-forward
Squash commit -- not updating HEAD
 .github/workflows/snyk_scan.yaml | 13 ++++++++++---
 1 file changed, 10 insertions(+), 3 deletions(-)

$ git commit
[snyk_scan_update 49f5c20] Squashed commit of the following:
 1 file changed, 10 insertions(+), 3 deletions(-)

$ git push --force origin HEAD
```

**Comment by cthorn42** [comment]
If https://github.com/puppetlabs/puppet-runtime/pull/515 gets merged this PR will need to add debian 12 armhf to the skip platform.

**Comment by joshcooper** [comment]
We're going to look at solving this a different way, closing for now.

**Pull request closed without merging**
