### PR TITLE
(PA-2055) Add vendored yaml-cpp and boost

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
Changes to support builds on AIX:
- AIX builds now fetch from artifactory, not OSMIRROR
- AIX builds now only specify build requirements in the platform file

### CODE REVIEW

**Comment by caseywilliams** [comment]
jenkins please test this with puppet-agent#master,puppet-agent#5.5.x on aix61-POWER,aix71-POWER,solaris10-SPARC,solaris10-64,solaris11-64,solaris11-SPARC

**Comment by McdonaldSeanp** [comment]
We won't be building on AIX 7.1, so that failure is expected

**Comment by McdonaldSeanp** [comment]
Ah, yeah, that's true. This may be blocked on https://tickets.puppetlabs.com/browse/PA-720 then

**Comment by ScottGarman** [comment]
I'm :+1:  on this, but won't merge it.

**Comment by McdonaldSeanp** [comment]
jenkins please test this with puppet-agent#master,puppet-agent#5.5.x on aix61-POWER,solaris10-SPARC,solaris10-64,solaris11-64,solaris11-SPARC

**Comment by McdonaldSeanp** [comment]
jenkins please test this with puppet-agent#master,puppet-agent#1.10.x on aix61-POWER,aix71-POWER

**Comment by McdonaldSeanp** [comment]
the above is expected to fail on agent#master for aix 7.1 (since we won't be building master on 7.1), otherwise things should all pass.

**Comment by McdonaldSeanp** [comment]
jenkins please test this with puppet-agent#master,puppet-agent#1.10.x on aix61-POWER,aix71-POWER

**Pull request merged**
