### PR TITLE
(FACT-1946) Build Solaris with ffi

### PR DESCRIPTION
**Pull request by sebastian-miclea**

### CODE REVIEW

**Comment by speedofdark** [comment]
Is this still really do-not-merge, please?

**Comment by GabrielNagy** [comment]
To get this working properly we need to:
- get `libffi6` for sparc architecture, this can be achieved on an i386 machine by using:
`pkgutil --stream --download -T sparc:5.10 libffi6` and `pkgtrans file.pkg /destdir` to unpack the downloaded `.pkg`
- modify rbconfig to use the sparc versions of libffi and libruby when linking
- modify rbconfig to use the toolchain from `/opt/pl-build-tools/sparc-sun-solaris2.10/bin` instead of `/usr/sfw/...` or `/opt/csw/...`
- ???

**Comment by GabrielNagy** [comment]
Got this working on Solaris 10 by monkey patching RubyGems before installing the ffi gem to require our custom RbConfig: https://github.com/puppetlabs/puppet-runtime/compare/master...GabrielNagy:solaris-ffi-sparc

This way we avoid changing environment variables too much, and the gem is installed correctly.

It *should* also work on Solaris 11 SPARC but I haven't tested it yet.

**Comment by GabrielNagy** [comment]
Closing this in favor of https://github.com/puppetlabs/puppet-runtime/pull/240.

**Pull request closed without merging**
