### PR TITLE
(PE-31670) Bump facter gem to 4.0.52

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
This builds fine.

**Comment by nicklewis** [comment]
Do we need to mirror this gem in https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/?

**Comment by donoghuc** [comment]
yes, any gem we add we must mirror. Also, this facter release does not contain all the fixes needed to satisfy the ticket.

**Comment by ekinanp** [comment]
Closing this until the relevant Facter release is out (one after the latest `4.0.52`).

**Pull request closed without merging**
