### PR TITLE
(maint) Bump puppet rubygem to 6.18.0

### PR DESCRIPTION
**Pull request by lucywyman**
Bumps the puppet rubygem to latest 6.18.0

### CODE REVIEW

**Comment by donoghuc** [comment]
Why is this bolt only?

**Comment by donoghuc** [comment]
We will need 6.18.0 in bolt-server runtime.

**Comment by lucywyman** [comment]
I wasn't sure if other teams were ready to pick up the latest Puppet, so wanted to make it optional. If everyone's ready to upgrade I can just update it. We have some work blocked on this in Bolt, so I'd like to get it in by Monday so we can release new features.

**Comment by donoghuc** [comment]
I think anybody that needs the puppet gem just needs latest bolt. I cant think of a reason not to bump it everywhere.

**Comment by lucywyman** [comment]
@donoghuc Just FYI I think we're gonna wait to merge this until the Bolt bits are ready to go, since they're mutually dependent and we need to do some rebasing since the PRs are so old.

**Pull request merged**
