### PR TITLE
(PA-3695) bump Ruby to 2.5.9 and 2.7.3

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by gimmyxd** [comment]
Jenkins please test agent-runtime-6.x,agent-runtime-main,pdk-runtime,pe-installer-runtime,bolt-runtime on all

**Comment by gimmyxd** [comment]
Jenkins please test agent-runtime-6.x,agent-runtime-main,pdk-runtime,pe-installer-runtime,bolt-runtime on all

**Comment by gimmyxd** [comment]
Jenkins please test agent-runtime-6.x on all

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#main on all

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#main on aix-7.1-ppc,el-6-x86_64,el-6-i386,el-7-x86_64,el-7-aarch64,el-8-x86_64,el-8-aarch64,debian-9-amd64,debian-9-i386,debian-10-amd64,fedora-30-x86_64,fedora-31-x86_64,fedora-32-x86_64,osx-10.14-x86_64,osx-10.15-x86_64,redhatfips-7-x86_64,sles-12-x86_64,sles-15-x86_64,solaris-11-i386,solaris-11-sparc,ubuntu-16.04-amd64,ubuntu-16.04-i386,ubuntu-18.04-amd64,ubuntu-20.04-amd64,ubuntu-20.04-aarch64,windows-2012r2-x64,windows-2012r2-x86,windowsfips-2012r2-x64

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on aix-7.1-ppc,el-6-x86_64,el-6-i386,el-7-x86_64,el-7-aarch64,el-8-x86_64,el-8-aarch64,debian-9-amd64,debian-9-i386,debian-10-amd64,fedora-30-x86_64,fedora-31-x86_64,fedora-32-x86_64,osx-10.14-x86_64,osx-10.15-x86_64,redhatfips-7-x86_64,sles-12-x86_64,sles-15-x86_64,solaris-11-i386,solaris-11-sparc,ubuntu-16.04-amd64,ubuntu-16.04-i386,ubuntu-18.04-amd64,ubuntu-20.04-amd64,ubuntu-20.04-aarch64,windows-2012r2-x64,windows-2012r2-x86,windowsfips-2012r2-x64

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main on aix-7.1-ppc,el-6-x86_64,el-6-i386,el-7-x86_64,el-7-aarch64,el-8-x86_64,el-8-aarch64,debian-9-amd64,debian-9-i386,debian-10-amd64,fedora-30-x86_64,fedora-31-x86_64,fedora-32-x86_64,osx-10.14-x86_64,osx-10.15-x86_64,redhatfips-7-x86_64,sles-12-x86_64,sles-15-x86_64,solaris-11-i386,solaris-11-sparc,ubuntu-16.04-amd64,ubuntu-16.04-i386,ubuntu-18.04-amd64,ubuntu-20.04-amd64,ubuntu-20.04-aarch64,windows-2012r2-x64,windows-2012r2-x86,windowsfips-2012r2-x64

**Comment by gimmyxd** [comment]
Jnekins please test this with puppet-agent#main on aix71-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,redhat6-64a,redhat6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windowsfips2012r2-64a

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#main on aix71-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,redhat6-64a,redhat6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windowsfips2012r2-64a

**Comment by gimmyxd** [comment]
vanagon generic builder for agent-runtime-6.x: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1080/

**Comment by gimmyxd** [comment]
jenkins please test this with puppet-agent#main on debian10-64a

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on debian10-64a

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on el-7-aarch64a

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on redhat7-AARCH64a,solaris11-SPARCa

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on redhat7-AARCH64a,solaris11-SPARCa

**Comment by gimmyxd** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on solaris11-SPARCa

**Comment by GabrielNagy** [comment]
jenkins please test agent-runtime-main with puppet-agent#main on redhat7-AARCH64a,solaris11-SPARCa

**Review by mihaibuzgau — APPROVED** [review]

**Review by mihaibuzgau — APPROVED** [review]

**Pull request merged**
