### PR TITLE
(PDK-1673) Update PDK OpenSSL to 1.1.1

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Review by ciprianbadescu — APPROVED** [review]

**Comment by scotje** [comment]
Building this now and then going to run it through PDK CI, but should be good.

**Comment by scotje** [comment]
I think the only issue here is that we are currently still building Ruby 2.1.9 for PDK and Ruby < 2.4 is not compatible with OpenSSL 1.1.x, but we were planning to drop that as part of the Puppet 7 addition anyway, so this might just have to wait until that other work is done.

**Comment by underscorgan** [comment]
Hey @scotje ! Just wanted to follow back up on this since puppet7 is out.

Thanks!

**Comment by underscorgan** [comment]
@jpogran can you take a look at this? Thank you!!

**Comment by jpogran** [comment]
We've stopped shipping ruby 2.1 in the PDK 2.0 release, so this should be good to merge, but I will check with @scotje just in case I missed some context

**Pull request merged**
