### PR TITLE
(BOLT-1583) Bump orchestrator_client gem

### PR DESCRIPTION
**Pull request by donoghuc**
Pull in bugfix for pcp timeout.

### CODE REVIEW

**Comment by rileynewton** [comment]
Looks like the bug fix hasn't been merged yet, https://github.com/puppetlabs/orchestrator_client-ruby/pull/31 - might need to do another release there too?

**Comment by donoghuc** [comment]
🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦

**Comment by donoghuc** [comment]
@rileynewton updated.

**Review by rileynewton — APPROVED** [review]
👍

**Pull request merged**
