### PR TITLE
(PA-3526) Ruby 2.7.2 performance patches

### PR DESCRIPTION
**Pull request by jpogran**
- (PA-3526) Patch Ruby 2.7.2 Avoid realpath in require

### CODE REVIEW

**Review by lucywyman — APPROVED** [review]
Successfully built an x64 MSI, installed on Windows 2019 just fine, and was able to create a project, run ruby-language tasks (`facts`), and run Puppet language plans.

**Comment by mihaibuzgau** [comment]
Puppet runtime builds for Puppet Agent 6.x for all the supported platforms are available here: http://builds.delivery.puppetlabs.net/puppet-runtime/d16928cda5c70f0548a97d7acdda6a10791dd5c4/

**Comment by mihaibuzgau** [comment]
Puppet Agent runtime for main build passed on all the supported. Artifacts are available here: http://builds.delivery.puppetlabs.net/puppet-runtime/d16928cda5c70f0548a97d7acdda6a10791dd5c4/

**Comment by mihaibuzgau** [comment]
tests passed on all platforms for Puppet 6.x: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/940/

**Comment by jpogran** [comment]
This is great news! I am working on getting a PDK build tested with these patches

**Comment by mihaibuzgau** [comment]
Tests passed on Puppet Agent main (7.x) with this change: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/942/

**Review by mihaibuzgau — APPROVED** [review]

**Comment by lucywyman** [comment]
Hmm, I'm trying to build PDK on Windows 2019 on this PR, and am running into a strange error:
```
configure: error: dtrace(1) is missing
Makefile:345: recipe for target 'ruby-2.4.10-configure' failed
make: *** [ruby-2.4.10-configure] Error 1
```
Anything I'm obviously doing wrong?

**Comment by lucywyman** [comment]
Hmmm new error building PDK-runtime:
```
16:46:53 Failures
16:46:53  - pl-toolchain-x64 - pl-toolchain-x64 not installed. The package was not found with the source(s) listed.
16:46:53  Source(s): 'https://artifactory.delivery.puppetlabs.net/artifactory/api/nuget/nuget'
```

**Comment by lucywyman** [comment]
:tada: :taco: :tada: Got a successful run for PDK!!

**Comment by joshcooper** [comment]
Yay! Could you reference PA-3526 in the commits. We're definitely going to want to mention this in release notes

**Comment by jpogran** [comment]
@joshcooper will do!

**Comment by jpogran** [comment]
Commit messages amended

**Review by joshcooper — APPROVED** [review]
@jpogran awesome thanks! Could you file a PA ticket so we remember to double check/revert commit 6a6886d when moving to ruby 2.7.3+ as it looks like that issue is fixed in upstream ruby (but not yet released): https://github.com/ruby/ruby/commit/99b4f20fd65075d2d9ee02f8c7a6b5d6a914ce31

Did you run into issues with the ruby patch for https://bugs.ruby-lang.org/issues/15856? I found it to be somewhat helpful in puppet, but don't remember exact numbers.

**Comment by jpogran** [comment]
Ticket https://tickets.puppetlabs.com/browse/PA-3691 created to track removing the patch when upstream ruby is merged into the released 2.7

**Comment by lucywyman** [comment]
\o/ Any other todo items left before we merge? It's fine if there are, I don't mean to pressure but happy to help get this across the line any way I can.

**Comment by jpogran** [comment]
I don't think there are any other open items. We have successfull runs in puppet-agent, bolt and pdk, I think this is ready for merge. 🚀 If everyone is ok with it, I'll self merge this 

The patch Josh is mentioning would be a separate PR.

**Comment by lucywyman** [comment]
Holding off on merging this until Puppet 7.6.0 is released later this month.

**Comment by joshcooper** [comment]
We had to bump to 2.7.3 for a ruby cve and I think commit 6a6886d can be dropped due to the issue being fixed upstream.

**Review by lucywyman — APPROVED** [review]

**Comment by lucywyman** [comment]
Is this ready to remove 'do not merge' label?

**Comment by joshcooper** [comment]
Is the "Add new Windows 2019 platform to dtrace ignore arrays" commit needed or is it for a different problem?

**Pull request merged**
